---
- hosts: local_hosts
  tasks:
    - name: Pull Docker image
      docker_image:
        name: krp277/scientific-calculator
        source: pull

    - name: Run Docker container
      docker_container:
        name: scientific_calculator
        image: krp277/scientific-calculator
        state: started
        restart_policy: always
